// IDL 文件 - 用于前端与智能合约交互
export const IDL = {
  version: "0.1.0",
  name: "tpot_p2p",
  instructions: [
    {
      name: "initialize",
      accounts: [
        { name: "platformConfig", isMut: true, isSigner: false },
        { name: "authority", isMut: true, isSigner: true },
        { name: "systemProgram", isMut: false, isSigner: false },
      ],
      args: [
        { name: "platformFee", type: "u64" },
        { name: "disputeFee", type: "u64" },
      ],
    },
    {
      name: "createBuyOrder",
      accounts: [
        { name: "order", isMut: true, isSigner: false },
        { name: "maker", isMut: true, isSigner: true },
        { name: "makerProfile", isMut: true, isSigner: false },
        { name: "tokenMint", isMut: false, isSigner: false },
        { name: "platformConfig", isMut: false, isSigner: false },
        { name: "systemProgram", isMut: false, isSigner: false },
      ],
      args: [
        { name: "orderId", type: "u64" },
        { name: "amount", type: "u64" },
        { name: "price", type: "u64" },
        { name: "paymentMethod", type: "string" },
        { name: "minLimit", type: "u64" },
        { name: "maxLimit", type: "u64" },
      ],
    },
    {
      name: "createSellOrder",
      accounts: [
        { name: "order", isMut: true, isSigner: false },
        { name: "escrow", isMut: true, isSigner: false },
        { name: "maker", isMut: true, isSigner: true },
        { name: "makerProfile", isMut: true, isSigner: false },
        { name: "makerTokenAccount", isMut: true, isSigner: false },
        { name: "escrowTokenAccount", isMut: true, isSigner: false },
        { name: "tokenMint", isMut: false, isSigner: false },
        { name: "platformConfig", isMut: false, isSigner: false },
        { name: "tokenProgram", isMut: false, isSigner: false },
        { name: "systemProgram", isMut: false, isSigner: false },
      ],
      args: [
        { name: "orderId", type: "u64" },
        { name: "amount", type: "u64" },
        { name: "price", type: "u64" },
        { name: "paymentMethod", type: "string" },
        { name: "minLimit", type: "u64" },
        { name: "maxLimit", type: "u64" },
      ],
    },
    {
      name: "takeOrder",
      accounts: [
        { name: "order", isMut: true, isSigner: false },
        { name: "escrow", isMut: true, isSigner: false },
        { name: "taker", isMut: true, isSigner: true },
        { name: "takerProfile", isMut: true, isSigner: false },
        { name: "takerTokenAccount", isMut: true, isSigner: false },
        { name: "escrowTokenAccount", isMut: true, isSigner: false },
        { name: "tokenMint", isMut: false, isSigner: false },
        { name: "platformConfig", isMut: false, isSigner: false },
        { name: "tokenProgram", isMut: false, isSigner: false },
        { name: "systemProgram", isMut: false, isSigner: false },
      ],
      args: [{ name: "orderId", type: "u64" }],
    },
    {
      name: "confirmPayment",
      accounts: [
        { name: "order", isMut: true, isSigner: false },
        { name: "payer", isMut: false, isSigner: true },
      ],
      args: [
        { name: "orderId", type: "u64" },
        { name: "paymentProof", type: "string" },
      ],
    },
    {
      name: "releaseTokens",
      accounts: [
        { name: "order", isMut: true, isSigner: false },
        { name: "escrow", isMut: true, isSigner: false },
        { name: "seller", isMut: false, isSigner: true },
        { name: "makerProfile", isMut: true, isSigner: false },
        { name: "takerProfile", isMut: true, isSigner: false },
        { name: "escrowTokenAccount", isMut: true, isSigner: false },
        { name: "buyerTokenAccount", isMut: true, isSigner: false },
        { name: "feeTokenAccount", isMut: true, isSigner: false },
        { name: "platformConfig", isMut: false, isSigner: false },
        { name: "tokenProgram", isMut: false, isSigner: false },
      ],
      args: [{ name: "orderId", type: "u64" }],
    },
    {
      name: "cancelOrder",
      accounts: [
        { name: "order", isMut: true, isSigner: false },
        { name: "escrow", isMut: true, isSigner: false },
        { name: "canceler", isMut: false, isSigner: true },
        { name: "cancelerProfile", isMut: true, isSigner: false },
        { name: "escrowTokenAccount", isMut: true, isSigner: false },
        { name: "makerTokenAccount", isMut: true, isSigner: false },
        { name: "sellerTokenAccount", isMut: true, isSigner: false },
        { name: "tokenProgram", isMut: false, isSigner: false },
      ],
      args: [{ name: "orderId", type: "u64" }],
    },
  ],
  accounts: [
    {
      name: "PlatformConfig",
      type: {
        kind: "struct",
        fields: [
          { name: "authority", type: "publicKey" },
          { name: "platformFee", type: "u64" },
          { name: "disputeFee", type: "u64" },
          { name: "totalVolume", type: "u64" },
          { name: "totalOrders", type: "u64" },
          { name: "paused", type: "bool" },
          { name: "bump", type: "u8" },
        ],
      },
    },
    {
      name: "Order",
      type: {
        kind: "struct",
        fields: [
          { name: "orderId", type: "u64" },
          { name: "maker", type: "publicKey" },
          { name: "taker", type: { option: "publicKey" } },
          { name: "orderType", type: { defined: "OrderType" } },
          { name: "tokenMint", type: "publicKey" },
          { name: "amount", type: "u64" },
          { name: "price", type: "u64" },
          { name: "totalValue", type: "u64" },
          { name: "paymentMethod", type: "string" },
          { name: "status", type: { defined: "OrderStatus" } },
          { name: "escrowAccount", type: "publicKey" },
          { name: "createdAt", type: "i64" },
          { name: "expiresAt", type: "i64" },
          { name: "paymentTime", type: { option: "i64" } },
          { name: "completedAt", type: { option: "i64" } },
          { name: "cancelledAt", type: { option: "i64" } },
          { name: "paymentProof", type: { option: "string" } },
          { name: "cancelReason", type: { option: "string" } },
          { name: "minLimit", type: "u64" },
          { name: "maxLimit", type: "u64" },
          { name: "bump", type: "u8" },
        ],
      },
    },
  ],
  types: [
    {
      name: "OrderType",
      type: {
        kind: "enum",
        variants: [
          { name: "Buy" },
          { name: "Sell" },
        ],
      },
    },
    {
      name: "OrderStatus",
      type: {
        kind: "enum",
        variants: [
          { name: "Pending" },
          { name: "Matched" },
          { name: "Paid" },
          { name: "Released" },
          { name: "Completed" },
          { name: "Cancelled" },
          { name: "Disputed" },
          { name: "Arbitrated" },
        ],
      },
    },
  ],
  errors: [
    { code: 6000, name: "InvalidAmount", msg: "Invalid amount" },
    { code: 6001, name: "InvalidPrice", msg: "Invalid price" },
    { code: 6002, name: "InvalidLimit", msg: "Invalid limit values" },
    { code: 6003, name: "PaymentMethodTooLong", msg: "Payment method too long" },
    { code: 6004, name: "PlatformPaused", msg: "Platform is paused" },
    { code: 6005, name: "OrderNotPending", msg: "Order not pending" },
    { code: 6006, name: "OrderAlreadyTaken", msg: "Order already taken" },
    { code: 6007, name: "OrderExpired", msg: "Order expired" },
    { code: 6008, name: "OrderNotMatched", msg: "Order not matched" },
    { code: 6009, name: "OrderNotPaid", msg: "Order not paid" },
  ],
};
